### PR TITLE
Create FAQ for goodbook review

### PR DESCRIPTION
**Pull request by gogunyemi1**
Hi, i thought of this has a valuable addition to this wonderful project.
review and merge, thank you

### CODE REVIEW

**Comment by code-with-sam** [comment]
Thanks. Good idea. Can you add this as a section in the readme instead?

**Comment by princekelly1** [comment]
Yes I can, I would add it to the previous readme as, updated readme?.
I should make a new pull for that?

**Comment by princekelly1** [comment]
Sorry not me, lol

**Comment by gogunyemi1** [comment]
Hello 
Thanks for the complement .. yes I can do that.. I will make a new pull out for that.. 
Thanks

**Comment by gogunyemi1** [comment]
Hello 
I want to inform you that I’ve added it as a section in the read me page.. I want you to check the new pull request and marge it if it’s okay by you. 
Thanks

**Comment by gogunyemi1** [comment]
Here is the link to the updated read me https://github.com/code-with-sam/goodbook.reviews/pull/9

**Comment by code-with-sam** [comment]
Not needed.

**Pull request closed without merging**
